enum Status {
  ok(0),
  cancelled(1),
  unknown(2),
  deadlineExceeded(4),
  permissionDenied(7),
  resourceExhausted(8),
  unimplemented(12),
  internal(13),
  unavailable(14),

  // following status codes are never generated by the library, only by user code.
  invalidArgument(3),
  notFound(5),
  alreadyExists(6),
  failedPrecondition(9),
  aborted(10),
  outOfRange(11),
  dataLoss(15);

  const Status(this.code);
  final int code;

  static Status from(int code) {
    final masked = code & 0xF;
    return Status.values.firstWhere((s) => s.code == masked);
  }

  @override
  String toString() => name;
}
