#[repr(u8)]
#[derive(Debug, Default, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Status {
    #[default]
    Ok = 0,
    Cancelled = 1,
    Unknown = 2,
    DeadlineExceeded = 4,
    PermissionDenied = 7,
    ResourceExhausted = 8,
    Unimplemented = 12,
    Internal = 13,
    Unavailable = 14,

    // following status codes are never generated by the library, only by user code.
    InvalidArgument = 3,
    NotFound = 5,
    AlreadyExists = 6,
    FailedPrecondition = 9,
    Aborted = 10,
    OutOfRange = 11,
    DataLoss = 15,
}

impl From<u8> for Status {
    #[inline]
    fn from(code: u8) -> Self {
        unsafe { std::mem::transmute(code & 0b_1111) }
    }
}

impl Status {
    #[inline]
    pub const fn code(self) -> u8 {
        self as u8
    }
}
