pub enum StatusCode {
    Ok = 0,
    Cancelled = 1,
    Unknown = 2,
    DeadlineExceeded = 4,
    PermissionDenied = 7,
    ResourceExhausted = 8,
    Unimplemented = 12,
    Internal = 13,
    Unavailable = 14,
    Unauthenticated = 16,

    // following status codes are never generated by the library, only by user code.
    InvalidArgument = 3,
    NotFound = 5,
    AlreadyExists = 6,
    FailedPrecondition = 9,
    Aborted = 10,
    OutOfRange = 11,
    DataLoss = 15,
}
